# Generated by Django 6.0.3 on 2026-03-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('modulo', models.CharField(max_length=40)),
                ('automacao_nome', models.CharField(max_length=120)),
                ('executor_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro'), ('stopped', 'Interrompida')], default='pending', max_length=20)),
                ('parametros_texto', models.TextField(blank=True)),
                ('mensagem_resumo', models.TextField(blank=True)),
                ('log_saida', models.TextField(blank=True)),
                ('arquivo_entrada', models.FileField(blank=True, null=True, upload_to='entradas/%Y/%m/%d/')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('interromper_solicitado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('attachment', 'Anexo'), ('output', 'Saida')], max_length=20)),
                ('arquivo', models.FileField(upload_to='automacoes/')),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.automationexecution')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
