# Generated by Django 6.0.3 on 2026-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_automationasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationasset',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Arquivo salvo da automação', 'verbose_name_plural': 'Arquivos salvos da automação'},
        ),
        migrations.AlterModelOptions(
            name='automationexecution',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Execução de automação', 'verbose_name_plural': 'Execuções de automação'},
        ),
        migrations.AlterModelOptions(
            name='automationexecutionfile',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Arquivo da execução', 'verbose_name_plural': 'Arquivos da execução'},
        ),
        migrations.AlterField(
            model_name='automationexecutionfile',
            name='tipo',
            field=models.CharField(choices=[('primary_input', 'Principal'), ('attachment', 'Anexo'), ('output', 'Saida')], max_length=20),
        ),
    ]
