# Generated by Django 6.0.3 on 2026-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_automationasset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationQueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_executions', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da fila de automações',
                'verbose_name_plural': 'Configurações da fila de automações',
            },
        ),
    ]
