# Generated by Django 6.0.3 on 2026-03-28 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentationpage',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
