# Generated by Django 6.0.3 on 2026-03-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentacao', '0002_documentationpage_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('created', 'Criação'), ('updated', 'Alteração'), ('status_changed', 'Mudança de status')], max_length=20)),
                ('titulo_snapshot', models.CharField(max_length=160)),
                ('raw_content_snapshot', models.TextField(blank=True)),
                ('rendered_html_snapshot', models.TextField(blank=True)),
                ('status_snapshot', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], max_length=20)),
                ('versao_snapshot', models.PositiveIntegerField(default=1)),
                ('object_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('automacao_nome_snapshot', models.CharField(blank=True, max_length=160)),
                ('campos_alterados', models.JSONField(blank=True, default=list)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('documentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='documentacao.documentationpage')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de documentação',
                'verbose_name_plural': 'Auditorias de documentação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
