# Generated by Django 6.0.3 on 2026-03-28 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0003_documentationauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationpage',
            options={'ordering': ['-atualizado_em'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.CreateModel(
            name='DocumentationViewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_interacao_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('tempo_permanencia_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('documentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='documentacao.documentationpage')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_view_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de visualização',
                'verbose_name_plural': 'Auditorias de visualização',
                'ordering': ['-aberto_em'],
            },
        ),
    ]
