# Generated by Django 6.0.3 on 2026-03-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0004_alter_documentationpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='publication_section',
            field=models.CharField(choices=[('system', 'Sistema'), ('administracao', 'Administração')], default='system', max_length=20),
        ),
    ]
