# Generated by Django 6.0.3 on 2026-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automacaoti',
            name='aceita_anexos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automacaoti',
            name='aceita_arquivo_entrada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automacaoti',
            name='executor_path',
            field=models.CharField(default='ti.automacoes.processar_inventario.executar', max_length=255),
        ),
        migrations.AddField(
            model_name='automacaoti',
            name='identificador',
            field=models.SlugField(default='ti', max_length=120),
        ),
    ]
